using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace ObjectPoolTest
{

	public class BulletController : MonoBehaviour
	{
		[SerializeField] private GameObject projectile;

		public KeyCode bulletSpawnKey; // 원하는 키 할당
        private ObjectPool objectPool;
        
        private void Awake()
        {
            objectPool = new ObjectPool(projectile);    // 5 개의 프리팹 생성후 비활성화
        }

        private void Update()
        {
            if (Input.GetKey(bulletSpawnKey))   // " " 키 입력시
            {
                // GameObject clone = Instantiate(projectile, transform.position, Quaternion.identity);

                // 생성할 때 AcitvatePoolItem을 이용해서 미리 만들어둔 오브젝트 풀 사용
                GameObject clone = objectPool.ActivatePoolItem();
                

                clone.GetComponent<Projectile>().SetUp(objectPool);
            }

            if (Input.GetKey(KeyCode.A))    // A키입력시 전체오브젝트 비활성화
            {
                objectPool.DeActivateAllPoolItem();
            }
        }
    }

}